#include "uzbl-core.h"

#include "../parser/uzbl.tab.h"
#include "../parser/uzbl.flex.h"

/*
int parse()
{
  YYSTYPE fake_it;
  yypstate *ps;
  yyscan_t scanner;
  int status;

  ps = yypstate_new();
  yylex_init(&scanner);

  */
  /*
   * current state of the push parser: The interface between scanner and
   * parsers works, but the semantic values are lost!
   * Send mail to the bison mailing list how to circumvent this.
   */
  /*
  do {
    memset(&fake_it, 0, sizeof(YYSTYPE));
    */
    /*
     * from the C source code generated by bison 2.4.3, one finds
     * that the third argument of yypush_parse takes a YYSTYPE
     * .
     * So it looks like this is the way how to pass the semantic
     * values from the scanner to the parser.
     */
    /*
    status = yypush_parse (ps, yylex(&fake_it, scanner), &fake_it);
  } while (status == YYPUSH_MORE);

  yylex_destroy(scanner);

  return 0;
}
*/
